[package]
name = "indicatif"
description = "A progress bar and cli reporting library for Rust"
version = "0.2.0"
keywords = ["cli", "progress", "pb", "colors", "progressbar"]
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
license = "MIT"
homepage = "https://github.com/mitsuhiko/indicatif"
documentation = "https://docs.rs/indicatif"
readme = "README.md"

[dependencies]
libc = "0"
parking_lot = "0"
regex = "0.2"
lazy_static = "0.2"
unicode-width = "0.1"
clicolors-control = "0"

[target.'cfg(windows)'.dependencies]
winapi = "0"
kernel32-sys = "0"
