[package]
name = "indicatif"
description = "A progress bar and cli reporting library for Rust"
version = "0.17.0-rc.1"
keywords = ["cli", "progress", "pb", "colors", "progressbar"]
categories = ["command-line-interface"]
license = "MIT"
repository = "https://github.com/mitsuhiko/indicatif"
documentation = "https://docs.rs/indicatif"
readme = "README.md"
edition = "2018"
exclude = ["screenshots/*"]

[dependencies]
number_prefix = "0.4"
console = { version = "0.15.0", default-features = false, features = ["ansi-parsing"] }
unicode-segmentation = { version = "1.6.0", optional = true }
unicode-width = { version = "0.1.7", optional = true }
rayon = { version = "1.0", optional = true }
tokio = { version = "1.0", optional = true, features = ["fs", "io-util"] }

[dev-dependencies]
once_cell = "1.8.0"
rand = "0.8"
structopt = "0.3"
tokio = { version = "1.0", features = ["time", "rt"] }

[features]
default = []
improved_unicode = ["unicode-segmentation", "unicode-width", "console/unicode-width"]

# Legacy alias for `rayon`
with_rayon = ["rayon"]
