name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, 1.51]
        features: [--all-features, ""]
        exclude:
          - os: macos-latest
            rust: stable
            features: ""
          - os: macos-latest
            rust: beta
            features: --all-features
          - os: macos-latest
            rust: beta
            features: ""
          - os: macos-latest
            rust: 1.51
            features: --all-features
          - os: macos-latest
            rust: 1.51
            features: ""
          - os: windows-latest
            rust: stable
            features: ""
          - os: windows-latest
            rust: beta
            features: --all-features
          - os: windows-latest
            rust: beta
            features: ""
          - os: windows-latest
            rust: 1.51
            features: --all-features
          - os: windows-latest
            rust: 1.51
            features: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace ${{ matrix.features }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        if: always()
        with:
          command: clippy
          args: --workspace --all-targets --all-features -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: EmbarkStudios/cargo-deny-action@v1
